frontend/rolecall/src/app/cast/cast-drag-and-drop.component.html, frontend/rolecall/src/app/cast/cast-drag-and-drop.component.scss, frontend/rolecall/src/app/cast/cast-drag-and-drop.component.ts
Adding image support based on first name and last name.
=> Adding cast images

.gitignore, frontend/rolecall/src/api_types.ts, frontend/rolecall/src/app/app/side_nav.component.ts, frontend/rolecall/src/app/cast/casting_editor.component.ts, frontend/rolecall/src/app/piece/piece_editor.component.ts, frontend/rolecall/src/colors.scss, frontend/rolecall/src/constants.ts, frontend/rolecall/src/index.html, frontend/rolecall/src/main.ts, frontend/rolecall/src/styles.scss, frontend/rolecall/src/test.ts, frontend/rolecall/src/types.d.ts
There should be no functional changes from this. If you suspect there might be, please point that out in review.
=> Minor cleanup on root level of frontend code while I explore how the app is built

frontend/rolecall/src/app/user/user-editor.component.html, frontend/rolecall/src/app/user/user-editor.component.scss, frontend/rolecall/src/app/user/user-editor.component.spec.ts, frontend/rolecall/src/app/user/user-editor.component.ts, frontend/rolecall/src/app/user/user-routing.module.ts, frontend/rolecall/src/app/user/user.module.ts, frontend/rolecall/tslint.json
There should be no functional changes from any of this. 
See description of each individual commit for details.
=> Cleaning up "user" frontend path.

frontend/rolecall/src/app/cast/cast-drag-and-drop.component.html, frontend/rolecall/src/app/cast/cast-drag-and-drop.component.scss, frontend/rolecall/src/app/cast/cast-drag-and-drop.component.ts, frontend/rolecall/src/app/cast/cast-editor-v2.component.html, frontend/rolecall/src/app/cast/cast-editor-v2.component.scss, frontend/rolecall/src/app/cast/cast-editor-v2.component.ts, frontend/rolecall/src/app/performance/performance-editor.component.ts, frontend/rolecall/src/std.scss, frontend/rolecall/src/styles.scss
Cleanup of the cast-drag-and-drop.component files and the cast-editor-v2.component files.
No (purposeful) logic changes.
=> Cast Cleanup

frontend/rolecall/src/app/cast/cast-editor-v2.component.scss, frontend/rolecall/src/app/piece/piece-routing.module.ts, frontend/rolecall/src/app/piece/piece.module.ts, frontend/rolecall/src/app/piece/piece_editor.component.html, frontend/rolecall/src/app/piece/piece_editor.component.scss, frontend/rolecall/src/app/piece/piece_editor.component.spec.ts, frontend/rolecall/src/app/piece/piece_editor.component.ts, frontend/rolecall/src/std.scss, frontend/rolecall/src/styles.scss
Hopefully these changes are straight forward. I have a small change in this code that I will put in after the cleanup has been approved.
=> Cleanup of piece directory (the 'Segment' screen)

backend/src/main/java/com/google/rolecall/ApplicationLoader.java, backend/src/main/java/com/google/rolecall/jsonobjects/UserInfo.java, backend/src/main/java/com/google/rolecall/models/User.java, backend/src/main/java/com/google/rolecall/services/UserServices.java
Alvin Ailey has several dancers who use their middle names actively (they are listed in programs etc.) and one dancer who has a suffix. In the past we could support this by adding extra names in the first name field and adding the suffix to the last name field.
With our new picture lookup logic, we can't edit either the first or last name fields any longer. Given that changing database structure creates access permission issues unless we wipe the database (which will be more difficult when we have active users with data), it makes sense to add the middle name and suffix fields now.
This code is very straight forward.
=> Backend Changes for capturing middle name and suffix

frontend/rolecall/src/app/piece/piece_editor.component.html, frontend/rolecall/src/app/piece/piece_editor.component.ts
This change sorts unfinished segments ahead of all finished segment. (An unfinished segment is one where no children have been specified.) Unfinished segments are also marked with a leading '*'.
=> better segment navigation

backend/src/main/java/com/google/rolecall/models/Section.java, frontend/rolecall/src/app/api/piece_api.service.ts, frontend/rolecall/src/app/performance/performance-editor.component.html, frontend/rolecall/src/app/performance/performance-editor.component.ts, frontend/rolecall/src/app/piece/piece_editor.component.html, frontend/rolecall/src/app/piece/piece_editor.component.ts
We thought REVELATION was a type, but it is only one of Mr Ailey's Super Ballets. The Alvin Ailey people prefer the type name 'Super Ballets'. We will use SUPER as the internal type name.
=> name change only: REVELATION -> SUPER

frontend/rolecall/src/app/cast/cast-drag-and-drop.component.html, frontend/rolecall/src/app/cast/cast-drag-and-drop.component.scss, frontend/rolecall/src/app/cast/cast-drag-and-drop.component.ts, frontend/rolecall/src/app/cast/cast-editor-v2.component.html, frontend/rolecall/src/app/performance/performance-editor.component.html
This is the smallest PR I could make to finish the dynamic setting of cast counts.
I have closed the other PRs relating to this.
=> basted on the last master, a minimum diff PR for finishing dynamic setting of #casts.

frontend/rolecall/src/app/cast/cast-drag-and-drop.component.html, frontend/rolecall/src/app/cast/cast-drag-and-drop.component.ts, frontend/rolecall/src/app/cast/cast-editor-v2.component.html, frontend/rolecall/src/app/mocks/mock_piece_backend.ts, frontend/rolecall/src/app/piece/piece_editor.component.html, frontend/rolecall/src/app/piece/piece_editor.component.scss, frontend/rolecall/src/app/piece/piece_editor.component.ts
This PR fixes two bugs and one big indentation error (which is big enough to confuse the diff. No logic changed but the diff is not so sure).
Bug one was fixed in a prior PR but the final implementation was lost.
Bug two causes the system to misbehave with empty segment lists.
=> fix two bugs and one indentation error

frontend/rolecall/src/app/cast/cast-drag-and-drop.component.ts, frontend/rolecall/src/app/cast/cast-editor-v2.component.ts, frontend/rolecall/src/app/performance/performance-editor.component.ts
More fixes to try to fix customer bug.
=> More fixes to try to fix customer bug

frontend/rolecall/angular.json, frontend/rolecall/src/app/cast/cast-drag-and-drop.component.scss, frontend/rolecall/src/app/cast/cast-editor-v2.component.scss, frontend/rolecall/src/app/performance/performance-editor.component.scss, frontend/rolecall/src/app/piece/piece_editor.component.scss, frontend/rolecall/src/app/services/header-utility.service.spec.ts, frontend/rolecall/src/app/services/logging.service.spec.ts, frontend/rolecall/src/app/services/logging.service.ts, frontend/rolecall/src/app/services/request-interceptor.service.spec.ts, frontend/rolecall/src/app/services/response-status-handler.service.spec.ts, frontend/rolecall/src/app/user/user-editor.component.scss, frontend/rolecall/tslint.json
- Fixed style import error when running ng test
- Fixed several service test failures
- Removed one redundant "logging" function that was not used
- Switched 'warn' and 'error' logging functions to log with the appropriate level instead of just 'info', and to properly print out any passed in objects
=> Fixing some test stuff

README.md, frontend/rolecall/src/app/app/app.component.spec.ts, frontend/rolecall/src/app/homepage/dashboard.component.spec.ts, frontend/rolecall/src/app/homepage/homepage_base.component.spec.ts, frontend/rolecall/src/app/login/welcome-page.component.spec.ts, frontend/rolecall/src/app/settings/settings_base.component.spec.ts
=> Fixed handful of tests

frontend/rolecall/src/app/cast/cast-drag-and-drop.component.ts, frontend/rolecall/src/app/performance/performance-editor.component.ts
I extracted the non controversial fixes in the last PR so that we can upload fixes so that the customer can use the system.
=> Fix client bug

frontend/rolecall/tsconfig.json
Added some placeholders for properties we should have, but cannot yet enable because our code has issues.
=> Increasing tsconfig strictness to reduce chance of bugs

frontend/rolecall/src/app/cast/cast-drag-and-drop.component.ts
I linted the cast director and fixed all complaints.
=> Linted the cast directory

frontend/rolecall/src/app/piece/piece_editor.component.ts
=> linted piece directory

frontend/rolecall/src/app/cast/cast-drag-and-drop.component.ts, frontend/rolecall/tsconfig.json
Minor cleanup in cast drag+drop component.
=> Enable noUnusedLocals and fix related issue

backend/src/main/java/com/google/rolecall/ApplicationLoader.java, frontend/rolecall/src/app/cast/cast-drag-and-drop.component.ts, frontend/rolecall/src/app/performance/performance-editor.component.ts
Some leftover fixes:
1) Remove some users from our temporary pre-populate list.
2) Secure selectCast so that calls with uuid being undefined don't wreak havoc with the system.
3) Some simple reformatting to match Mikhail's constructor formatting.
4) Removal of a cast to any.
=> Some leftover fixes

frontend/rolecall/src/app/services/csv-generator.service.ts
There is two remaining lint errors that I don't know the best way to fix.
=> Fix lint errors in csv-generator.service.ts

frontend/rolecall/src/app/app/side_nav.component.scss, frontend/rolecall/src/app/cast/cast-editor-v2.component.scss, frontend/rolecall/src/app/homepage/dashboard.component.scss, frontend/rolecall/src/styles/_constants.scss
=> adjust css for ipad

frontend/rolecall/src/app/common_components/stepper.component.scss, frontend/rolecall/src/styles/_colors.scss
I made a mistake with the color change earlier today.
And because of the switching between versions / branches, I missed the syntax error. (My system was building another branch).
=> Fix of bad css change from earlier

backend/src/main/java/com/google/rolecall/restcontrollers/AsyncRestEndpoint.java, backend/src/main/java/com/google/rolecall/restcontrollers/CurrentUser.java, backend/src/main/java/com/google/rolecall/restcontrollers/DashboardManagement.java, backend/src/main/java/com/google/rolecall/restcontrollers/SectionManagement.java, backend/src/main/java/com/google/rolecall/restcontrollers/UnavailabilityManagement.java, backend/src/main/java/com/google/rolecall/restcontrollers/UserManagement.java, backend/src/main/java/com/google/rolecall/services/PerformanceServices.java, backend/src/main/resources/application-clouddev.properties
I went trough the old open branches and found Jared's last changes.
Almost all of them are new comments or changes to comments. However, at the very end, he wanted to change some cloud setup parameters.
I copied all changes over to the new master and copied the configuration changes as comments to the configuration file.
Because the two of you are our configuration experts: Zephyr, the outgoing one and Richard, the incoming one, I asked both of you to be reviewers of this PR.
If you can tell me what you want to do regarding the configuration, I will make the parameter changes you want.
=> Jared's last changes

backend/pom.xml, backend/src/main/java/com/google/rolecall/ApplicationLoader.java, backend/src/main/java/com/google/rolecall/authentication/CustomDebugAuthenticationProvider.java, backend/src/main/java/com/google/rolecall/authentication/CustomOauthAuthenticationProvider.java, backend/src/main/java/com/google/rolecall/config/DataSourceConfig.java, backend/src/main/java/com/google/rolecall/config/RepositoryConfig.java, backend/src/main/java/com/google/rolecall/services/GoogleAuthServices.java, backend/src/main/resources/application-qa.properties, frontend/rolecall/angular.json, frontend/rolecall/package.json, frontend/rolecall/src/environments/environment.prod.ts, frontend/rolecall/src/environments/environment.qa.ts, package.json, yaml_backend/app_backend_prod.yaml, yaml_backend/app_backend_test.yaml, yaml_cloudbuild/cloudbuild_prod.yaml, yaml_cloudbuild/cloudbuild_test.yaml, yaml_frontend/app_frontend.yaml, yaml_frontend/app_frontend_prod.yaml, yaml_frontend/app_frontend_test.yaml
Organizing prod and cloud CICD environments
=> Organizing prod and cloud CICD environments

backend/src/main/java/com/google/rolecall/Constants.java, backend/src/main/java/com/google/rolecall/models/User.java, backend/src/main/java/com/google/rolecall/services/UserServices.java, backend/src/main/resources/application-dev.properties, backend/src/test/java/com/google/rolecall/ApplicationLoaderUnitTests.java, backend/src/test/java/com/google/rolecall/config/WebSecurityUnitTests.java, backend/src/test/java/com/google/rolecall/restcontrollers/UserManagementUnitTests.java, backend/src/test/java/com/google/rolecall/services/UserServiceTests.java, backend/src/test/java/com/google/rolecall/util/DefaultUsers.java, frontend/rolecall/package.json
I made the backed errors run without errors.
=> fix backend test errors

frontend/rolecall/src/app/api/piece_api.service.ts, frontend/rolecall/src/app/app/app.component.html, frontend/rolecall/src/app/cast/cast-editor-v2.component.html, frontend/rolecall/src/app/cast/cast-editor-v2.component.scss, frontend/rolecall/src/app/cast/cast-editor-v2.component.spec.ts, frontend/rolecall/src/app/cast/cast-editor-v2.component.ts, frontend/rolecall/src/app/cast/cast.module.ts, frontend/rolecall/src/app/mocks/mock_piece_backend.ts, frontend/rolecall/src/app/performance/performance-editor.component.html, frontend/rolecall/src/app/performance/performance-editor.component.scss, frontend/rolecall/src/app/performance/performance-editor.component.ts, frontend/rolecall/src/app/piece/piece_editor.component.html, frontend/rolecall/src/app/piece/piece_editor.component.scss, frontend/rolecall/src/app/piece/piece_editor.component.spec.ts, frontend/rolecall/src/app/piece/piece_editor.component.ts, frontend/rolecall/src/app/services/segment-display-list.service.spec.ts, frontend/rolecall/src/app/services/segment-display-list.service.ts, frontend/rolecall/src/styles/segment-left.scss, frontend/rolecall/src/styles/std.scss
This is a large PR. The customer wasn't happy with the inconsistent navigation we had in the different tabs, especially between the Segments tab and the Casts tab.
I addressed this by building a generic navigation object from the segment navigator (which was better than the cast navigator). In doing this, I had to move a lot of code around, which makes for lots of diffs.
Richard, in my experience with Mikhail, I know that he hates these big PRs (he likes to go really deep on smaller checkins), so I am only asking you to review this one. From my perspective, it is OK if a bug or two slip by. Right now, we only have two users at Alvin Ailey, and they are very forgiving. It is more important that they get to play with the code soon, rather than that we give them perfect code significantly …
=> Build standard navigation

frontend/rolecall/src/app/api/login_api.service.ts, frontend/rolecall/src/app/app/site_header.component.spec.ts, frontend/rolecall/src/app/mocks/mock_gapi.ts
=> Fixed FE tests related to logging in.

frontend/rolecall/src/app/cast/cast-editor-v2.component.spec.ts
I also commented out the offending console.log statement.
=> fix unit test bug

backend/pom.xml
Update springboot as associated vulnerable dependencies. Update hibernate to new maven repo location. Tested locally but not in cloud yet.
=> Update springboot to version 2.6.6

.gitignore, backend/.gitignore, backend/src/main/java/com/google/rolecall/restcontrollers/UnavailabilityManagement.java, frontend/rolecall/package-lock.json, frontend/rolecall/src/app/api/unavailability-api.service.ts, frontend/rolecall/src/app/mocks/mock_unavailability_backend.ts, frontend/rolecall/src/app/piece/piece_editor.component.scss, frontend/rolecall/src/app/unavailability/unavailability-editor.component.html, frontend/rolecall/src/app/unavailability/unavailability-editor.component.scss, frontend/rolecall/src/app/unavailability/unavailability-editor.component.ts, frontend/rolecall/src/app/unavailability/unavailability.module.ts
Fixed Unavailability screen as well as backend.
=> Standardized UX

backend/src/main/java/com/google/rolecall/config/DataSourceConfig.java, backend/src/main/java/com/google/rolecall/config/WebSecurityConfig.java
Secret manager is not being closed property and may be causing the crashes.
=> Close secret manager

backend/src/main/java/com/google/rolecall/restcontrollers/ProfilePictureManagement.java, frontend/rolecall/src/app/api/user-api.service.ts, frontend/rolecall/src/app/segment/segment-editor.component.ts, frontend/rolecall/src/app/services/response-status-handler.service.ts, frontend/rolecall/src/app/user/user-editor.component.ts, frontend/rolecall/src/app/utils/data-cache.ts
fixed user screen initialization error
fixed segment screen left list initialization error
=> qa fixes 01
